// Generated by Qodo Gen

import State from "@/domain/vo/state";

describe("State", () => {
  // Creating a State instance with a valid state code initializes correctly
  it("should initialize correctly when given a valid state code", () => {
    const state = new State("SP");
    expect(state.getValue()).toBe("SP");
  });

  // Constructor throws an error for an empty string
  it("should throw an error when given an empty string", () => {
    expect(() => new State("")).toThrow(
      "Invalid state: The name must contain in list of brazilian states"
    );
  });

  // getValue method returns the correct state code
  it("should return the correct state code when initialized with a valid state code", () => {
    const state = new State("SP");
    expect(state.getValue()).toBe("SP");
  });

  // Constructor does not throw an error for valid state codes
  it("should not throw an error when initializing with a valid state code", () => {
    expect(() => new State("SP")).not.toThrow();
  });

  // Constructor throws an error for a null value
  it("should throw an error when value is null", () => {
    expect(() => new State(null as any)).toThrow(
      "Invalid state: The name must contain in list of brazilian states"
    );
  });

  // Constructor throws an error for an undefined value
  it("should throw an error when value is undefined", () => {
    expect(() => new State(undefined as any)).toThrow(
      "Invalid state: The name must contain in list of brazilian states"
    );
  });

  // Constructor throws an error for a non-string input
  it("should throw an error when initialized with a non-string value", () => {
    expect(() => new State(123 as any)).toThrow(
      "Invalid state: The name must contain in list of brazilian states"
    );
  });

  // Constructor throws an error for a lowercase valid state code
  it("should success for lowercase state code", () => {
    expect(() => new State("sp")).not.toThrow();
  });

  // Constructor throws an error for a state code not in the list
  it("should throw an error for an invalid state code", () => {
    expect(() => new State("XYZ")).toThrow(
      "Invalid state: The name must contain in list of brazilian states"
    );
  });

  // Constructor handles whitespace around valid state codes
  it("should handle whitespace around valid state code", () => {
    const state = new State("  SP  ");
    expect(state.getValue()).toBe("SP");
  });

  // Constructor handles mixed case valid state codes
  it("should initialize correctly when given a mixed case valid state code", () => {
    const state = new State("sP");
    expect(state.getValue()).toBe("sP");
  });

  // Constructor handles special characters in state codes
  it("should throw error when given an invalid state code with special characters", () => {
    expect(() => new State("!@#")).toThrow(
      "Invalid state: The name must contain in list of brazilian states"
    );
  });

  // Constructor handles numeric strings as input
  it("should throw an error when initialized with a numeric string", () => {
    expect(() => new State("123")).toThrow(
      "Invalid state: The name must contain in list of brazilian states"
    );
  });
});
